Failed attempt to use playwright
Failed because playwright doesn't like to import ES Modules:
```
npm test

> test
> playwright test

Error: require() of ES Module /Users/andy/-/code/3rdparty/Babylon.js/packages/public/@babylonjs/core/Audio/v2/webAudio/webAudioEngine.js from /Users/andy/-/code/microsoft/240709-audio-engine-v2-testing-esm/tests/webAudioStaticSound.test.ts not supported.
Instead change the require of webAudioEngine.js in /Users/andy/-/code/microsoft/240709-audio-engine-v2-testing-esm/tests/webAudioStaticSound.test.ts to a dynamic import() which is available in all CommonJS modules.

   at webAudioStaticSound.test.ts:3

  1 | import { CreateAudioEngineAsync } from "@babylonjs/core/Audio/v2/webAudio/webAudioEngine";
  2 | import { CreateSoundBufferAsync } from "@babylonjs/core/Audio/v2/webAudio/webAudioStaticSound";
> 3 | import { expect, test } from "@playwright/test";
    |                       ^
  4 |
  5 | test("StaticSoundBuffer", async ({ page }) => {
  6 |     console.log("Running WebAudioStaticSound tests...");

    at Object.<anonymous> (/Users/andy/-/code/microsoft/240709-audio-engine-v2-testing-esm/tests/webAudioStaticSound.test.ts:3:23)
Error: No tests found
```